#!/usr/bin/env python3
"""solve_scrambler2.py - enumerate LFSR CONVENTIONS against the printed vector.

solve_scrambler.py showed the naive reading admits no 8-distinct-stage tap set.
The unknowns are conventions, not physics, so enumerate them explicitly:
  * shift direction (X_{i+1}<-X_i, or X_i<-X_{i+1})
  * seed orientation (X1 = LSB of 0xF180, or X1 = MSB)
  * feedback tap set: the printed exponents, or their reciprocal (16-k) -
    both are legitimate readings of "G(x) = 1+X+X^3+...+X^16" depending on
    whether the register is indexed with or against the polynomial
  * Galois form as well as Fibonacci
Oracle: the spec's own printed 24-bit sequence. A config "solves" only if some
assignment of 8 DISTINCT stages to D7..D0 reproduces all 24 bits.
"""
import itertools

SEED_HEX = 0xF180
PRINTED = [1, 3, 6, 7, 11, 12, 13, 16]
RECIP = sorted({16 - e for e in PRINTED if 0 < 16 - e <= 16} | {16})
VEC = "110000000110110100111111"


def seed_reg(orient):
    b = [(SEED_HEX >> i) & 1 for i in range(16)]        # b[0] = LSB
    if orient == "lsb_first":
        return {i + 1: b[i] for i in range(16)}
    return {i + 1: b[15 - i] for i in range(16)}


def step(R, direction, taps, form):
    N = dict(R)
    if form == "fib":
        fb = 0
        for t in taps:
            fb ^= R[t]
        if direction == "up":
            for i in range(16, 1, -1):
                N[i] = R[i - 1]
            N[1] = fb
        else:
            for i in range(1, 16):
                N[i] = R[i + 1]
            N[16] = fb
    else:                                               # galois
        if direction == "up":
            out = R[16]
            for i in range(16, 1, -1):
                N[i] = R[i - 1] ^ (out if i in taps else 0)
            N[1] = out
        else:
            out = R[1]
            for i in range(1, 16):
                N[i] = R[i + 1] ^ (out if i in taps else 0)
            N[16] = out
    return N


def histories(direction, taps, form, orient, n=3):
    R = seed_reg(orient)
    h = {i: [] for i in range(1, 17)}
    for _ in range(n):
        for i in range(1, 17):
            h[i].append(R[i])
        R = step(R, direction, taps, form)
    return h


def try_config(direction, taps, form, orient):
    h = histories(direction, taps, form, orient)
    need = {}
    for t in range(3):
        for j, ch in enumerate(VEC[t * 8:(t + 1) * 8]):
            need.setdefault(7 - j, []).append(int(ch))
    cands = []
    for d in range(8):
        want = tuple(need[d])
        fits = [s for s in range(1, 17) if tuple(h[s]) == want]
        if not fits:
            return []
        cands.append(fits)
    sols = []
    for combo in itertools.product(*cands):
        if len(set(combo)) == 8:
            sols.append({d: combo[d] for d in range(8)})
    return sols


if __name__ == "__main__":
    hits = 0
    for direction in ("up", "down"):
        for form in ("fib", "galois"):
            for tname, taps in (("printed", PRINTED), ("reciprocal", RECIP)):
                for orient in ("lsb_first", "msb_first"):
                    sols = try_config(direction, taps, form, orient)
                    if sols:
                        hits += 1
                        print(f"SOLVES: shift={direction} form={form} "
                              f"taps={tname}{taps} seed={orient} "
                              f"-> {len(sols)} tap set(s)")
                        for s in sols[:3]:
                            print("        D7..D0 =",
                                  [f"X{s[d]}" for d in range(7, -1, -1)])
    print(f"\n{hits} configuration(s) reproduce the printed 24-bit vector "
          f"with 8 distinct output stages.")
    if not hits:
        print("NONE — the inconsistency is not a convention choice; it is in "
              "the spec's own figure/vector pair (erratum), or the vector is "
              "generated by something other than a plain 16-stage tap read.")
